#!/usr/bin/env php
<?php

declare(strict_types=1);

require_once __DIR__ . '/../vendor/autoload.php';

use Ahc\Env\Loader;
use App\Infrastructure\DependencyInjection\ServiceContainer;

$envLoader = new Loader();
$envLoader->load(__DIR__ . '/../.env', true, Loader::ALL);

$container = ServiceContainer::load();
